### ISSUE TITLE
Publishing should cost a variable amount of FLO equal to a set USD value

### ISSUE THREAD

**Issue by DevonJames** [dloa/alexandria-browser#12]
Currently publishing only requires that a user spend the normal tx-fee for each transaction sent. In order to allow Alexandria's anti-spam minimum cost to remain independent of Florincoin's anti-spam minimum cost, the rules that govern publishing cost should be denominated in USD. The actual USD amount will vary over time until we find the right balance, but it should start at $0.01.

*note* the USD price to publish will be a variable determined by the Alexandria Council of Librarians

**Comment by DevonJames** [comment]
prerequisite for this issue: https://github.com/dloa/libraryd/issues/8

**Comment by OstlerDev** [comment]
Will be taken care of over there.
