### ISSUE TITLE
Tip Amount entry

### ISSUE THREAD

**Issue by lightsplasher** [dloa/alexandria-browser#18]
When entering a tip amount in the text box for Florincoin if a period is entered a pop up shows requesting you enter a number, so $0.01 can't be easily entered as an "other" amount (the existing period must not be deleted - maybe prevent it from being deleted from text field?).  Reproduce by highlighting existing $5.00 entry and then typing a period using Firefox browser under Ubuntu 14.04.

![tipissue](https://cloud.githubusercontent.com/assets/4122024/11104635/ca54d37e-887e-11e5-9241-774d8d102b02.jpg)

**Comment by DevonJames** [comment]
Hmmm... I dont have this problem - Chrome browser on Mac OSX 10.10.1
<img width="480" alt="screen shot 2015-11-11 at 2 21 34 pm" src="https://cloud.githubusercontent.com/assets/7625406/11104776/9e5f5342-887f-11e5-852e-c3c526b7c41e.png">

**Comment by copernicus-mogley** [comment]
I can't replicate this in debian or OSX.
