### ISSUE TITLE
Basic web-based publishing interface for media type: Video

### ISSUE THREAD

**Issue by DevonJames** [dloa/alexandria-browser#21]
Note:<field name> indicates the JSON field name to use in publish message.

###Fields to include in interface:

Publisher address: If user has previously announced a publisher, display a list, which includes the choice "announce a new publisher", if they have not, only display this choice. <publisher>
(http://api.alexandria.io/#announce-new-publisher)

Dropzone for video file

Video Info:
Video Title <alexandria-media:extra-info:displayName>
Video Description <alexandria-media:description> 
Creation Year <alexandria-media:year>
Artist <alexandria-media:extra-info:artist>
Company (optional) <alexandria-media:extra-info:company>
Tags (optional) <alexandria-media:extra-info:tags>

Payments Info:
BTC Payment Address <alexandria-media:payment:paymentAddress>
Suggested Price to Play (in USD) <alexandria-media:payment:suggPlayPrice[]>
Minimum Price to Play (in USD) <alexandria-media:payment:minPlayPrice[]>
Suggested Price to Buy (in USD) <alexandria-media:payment:suggBuyPrice[]>
Minimum Price to Buy (in USD) <alexandria-media:payment:minBuyPrice[]>
Suggested Tip (3 values, in USD) <alexandria-media:payment:suggTips[1,2,3]>
Promoters Rate (0-100%) <alexandria-media:payment:promotersRate>

Pin to Play:
Number of users at any given time who can play for free in exchange for pinning video to help provide storage & bandwidth <alexandria-media:payment:pinToPlay:ptpFreeThreshold>
Number of users at any given time who can play for a discount in exchange for pinning video to help provide storage & bandwidth <alexandria-media:payment:pinToPlay:ptpDiscThreshold>
Discount Amount for this group of users (0-100%) <alexandria-media:payment:pinToPlay:ptpDiscAmount>

Fields to generate with scripts or functions to include in publish message:

IPFS location hash (of directory that video file is in, ie: use -w flag when `ipfs add`)
<unixtime> current unixtime
<filename> get from file
<runtime> (in seconds) get from file, otherwise include in interface fields
<signature> generate from publish message contents
http://api.alexandria.io/#sign-artifact-publish-message

Fields to include with all publish messages:
<alexandria-media:type>:"video"
<alexandria-media:payment:fiat>:"USD"
<alexandria-media:payment:paymentToken>:"BTC"

Publish Artifact API: http://api.alexandria.io/#publish-new-artifact

**Comment by OstlerDev** [comment]
Taken care of at https://github.com/dloa/publisher-web
