### ISSUE TITLE
Artifact playlist display and functionality

### ISSUE THREAD

**Issue by copernicus-mogley** [dloa/alexandria-browser#29]
1. Disable playback of file on click in playlist when it has a cost. Double-check PWYW wall functionality in these cases.

2. When either price (play/download) is set and the other is not, remove the empty one from payment options. This will restrict publishers from PWYW downloads + free play ... Only if price to play is set and price to download is not, hide download purchase option.

**Comment by OstlerDev** [comment]
These features will be implemented after they are implemented in the publisher, users will be able to specify if they want purchasing or playing disabled along with prices for each file.

**Comment by cchrysostom** [comment]
See if this pull request fits the bill: https://github.com/dloa/alexandria-browser/pull/33
