### ISSUE TITLE
Paywall Use jQuery QRCode

### ISSUE THREAD

**Issue by cchrysostom** [dloa/alexandria-browser#42]
[media.js setQR](https://github.com/dloa/alexandria-browser/blob/master/src/app/js/media.js#L776) makes an external call to api.qrserver.com to generate a QR Code image in the paywall. Adjust this method to use the internal javascript to create image to reduce cross site scripting. Chris can make this change.

**Comment by OstlerDev** [comment]
This is what I use currently and I highly suggest it. It is used in several other DLOA apps https://davidshimjs.github.io/qrcodejs/

**Comment by cchrysostom** [comment]
Thanks. I did find qrcodejs. But, although jQuery QRCode is old, now, it is used in several places around Browser. I hesitate introducing another library unless @copernicus-mogley wants to swap it out. I do agree we should minimize calls to external web API's, though.

**Comment by cchrysostom** [comment]
This [pull request](https://github.com/dloa/alexandria-browser/pull/43) addresses the issue.
