### ISSUE TITLE
Bitcoin payments never received by publisher

### ISSUE THREAD

**Issue by copernicus-mogley** [dloa/alexandria-browser#67]
Payproc supposed to forward to:
179f7jU42vdYTG2v8unZo6i5pS9VmJ9F3q

Payproc payment addresses:
3Fg6cmhFRQQQ7FveYZqEq4ztiV1z27dn4h
3QWPHrTsAN7osUbjVwRt4B7L58KnFswVSi
34jt9SFEcJYhgAAhU7EnNrjj42zCj5AWtr

Artifact in question: https://alexandria.io/browser/#/53fd162d7a769ba79f2b285fc42a8de4a7a0b47de2ec1d9f9654ed9a176a20c4

**Comment by cchrysostom** [comment]
I created a utility to forward payments manually. In a recent run, it looks like a transaction sent payments to the publisher address. https://blockchain.info/address/179f7jU42vdYTG2v8unZo6i5pS9VmJ9F3q
